### ISSUE TITLE
ItemClasses > CanBeCorrupted is not correct

### ISSUE THREAD

**Issue by evanwarner** [poe-tool-dev/dat-schema#41]
The supposed purpose of [this column](https://github.com/poe-tool-dev/dat-schema/blob/main/dat-schema/_Core.gql#L2174) is not correct. All Heist equipment can be corrupted, all Leaguestones are inherently corrupted, and it looks like rare mod conversion can generate corrupted flasks, but these rows all have a `false` value. Something else is going on with this column.

**Comment by evanwarner** [comment]
I suppose it may just be `CanBePlayerCorrupted` actually, as Vaal Orb's definitely don't work on Heist gear or flasks.

**Comment by SnosMe** [comment]
I prefer not to change it. Tbh items can have a lot of anomalies and server is the only source of truth. And all these tables are to reduce round-trips to server. Considering ggg can change loot generation serverside all those columns should be prefixed `CanBeByPlayer` for future-proofing 😄
