### ISSUE TITLE
Separate .gql file per table in poe2?

### ISSUE THREAD

**Issue by makhotkin** [poe-tool-dev/dat-schema#88]
What do you think of switching to single file per table basis for the poe2 tables?

The advantage is in easier diffs and no need to order table across the whole file (they were sorted alphabeteically in _Core gql for poe1)

It's easy to switch now while the number of tables is still small

**Comment by SnosMe** [comment]
At maximum I'd propose to split _Core into files that span a logically related tables.
For leagues it's simple and alreay done, but for the _Core... tree,gems,ui,mtx

Another note is Github is bad at showing a lot of files, like try to open this https://github.com/adainrivers/poe2-datconverter/tree/main/src/Generated/Structs

**Comment by makhotkin** [comment]
Splitting into groups is even worse that not splitting at all - newcomes won't figure out to which group a file would belong. 
Looking at a large number of files in GitHub is not that bad at all, viewing experience depends on your screen size actually. 

Moreover, I consider generating .cs classes for each table a suboptimal practice, because you won't need 90% of them, and  that format when each field is decribed by multiple lines (attributes, the very field declaration, an empty line after) is simply hard to read. GQLs are good - you have a single line per field.

**Comment by aang521** [comment]
I think keeping the _Core file is fine.
The main issue with diffs is when you have a merge where a new table is added on both commits, which doesnt happen that often. If you are just editing a table the diffs are fine.
With regards to the sorting, I dont mind if it isnt sorted, I search for the tables anyway (and if they were seperate file i would still have to search for the correct file)

**Comment by lvlvllvlvllvlvl** [comment]
l don't have a strong opinion about this issue. Github ui truncates directories with 1000 files or more; the link above has 800, which is below that limit but not by much.

**Comment by adainrivers** [comment]
I'd say either a single file per PoE1 and PoE2, or per game per table. That would make it much clearer for the people who wants to contribute. 

In my case, I wanted to use these schemas as the main source of truth, but I couldn't figure out what is where. Now it's already clearer with the separate PoE2 folder.

**Comment by Vilsol** [comment]
One option might be to organize it into a directory structure like it is internally at GGG: 
![image](https://github.com/user-attachments/assets/66f70f17-89b7-4dbd-b0f9-80029b6f6e6d)

**Comment by SnosMe** [comment]
For the sake of clean single table history and easier merges, I agree to move `poe2/` to a file per table. Poe1 will remain as it is for now.

**Comment by SnosMe** [comment]
Done by #92
