### ISSUE TITLE
rids in ItemClasses were changed to enum table names (i32)

### ISSUE THREAD

**Issue by brather1ng** [poe-tool-dev/dat-schema#9]
#7 changed two rid fields in ItemClasses to enum references (`ItemClassCategory` and `ItemStance`). Since the schema file generation turns enum references into i32s, the schema for the table is now smaller than before.

I'm not sure what the best course of action would be here. Since there are probably more of these cases and there is also at least one the other way around (enum-like reference to a type, `Maps.MapSeriesKey`), maybe some directive for the special cases that allows overriding how the schema generator handles the reference (e.g. `@typeReference` and `@enumReference`)?

**Comment by SnosMe** [comment]
These two tables has data in rows, therefore they aren't enums. Maybe Einjin got it wrong what enum mean. They should be just edited back to table type (keyword `type` in file) and obviously we're better to define what columns they contain.

**Comment by brather1ng** [comment]
ItemClassCategories was already there as an enum before. But yeah, if both have data, just changing them would be enough.
